on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://github.com/Eunice2000/alx-backend-javascript'
        env:
          JAVA_OPTS: "-Xmx5g"  # Increases the Java heap size to 2 GB
# Increases the Java heap size to 2 GB
